import Head from "next/head";
import { useState } from "react";
import { AppContext } from "@/context/appContext";

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => {

  const [phrase, setPhrase] = useState('')
  const [placesList, setPlacesList] = useState([])

  return (
    <>
      <Head>
        <title>Places I want to visit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContext.Provider value={{ phrase, setPhrase, placesList, setPlacesList }}>
        <main>{children}</main>
      </AppContext.Provider>
    </>
  );
};

export default Layout;
